// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package tr.com.anadolubank.grpc.proto;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tr.com.anadolubank.grpc.proto.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
